const path = require("path");

// ---------------------------------------------------------------------------
// ROOT PATHS
// ---------------------------------------------------------------------------

const VAULT_ROOT = "/Users/candice/4 - Organisation/obsidian-vault";

const PATHS = {
  vault: VAULT_ROOT,
  dailyNotes: path.join(VAULT_ROOT, "07 NOTES QUOTIDIENNES"),
  accueil: path.join(VAULT_ROOT, "🏠 Accueil.md"),
  aClasser: path.join(VAULT_ROOT, "ressources/À classer.md"),

  // Wish list destination files
  aVoir: path.join(VAULT_ROOT, "05 WISH LISTS/01 Reco culturelles/À voir.md"),
  aLire: path.join(VAULT_ROOT, "05 WISH LISTS/01 Reco culturelles/À lire.md"),
  aEcouter: path.join(VAULT_ROOT, "05 WISH LISTS/01 Reco culturelles/À écouter.md"),
  autres: path.join(VAULT_ROOT, "05 WISH LISTS/01 Reco culturelles/Autres.md"),
  partages: path.join(VAULT_ROOT, "05 WISH LISTS/01 Reco culturelles/Partages.md"),
};

// ---------------------------------------------------------------------------
// DAILY NOTES SETTINGS
// ---------------------------------------------------------------------------

const DAILY_NOTES = {
  // Date format used in daily note filenames (YYYY-MM-DD.md)
  filePattern: /^\d{4}-\d{2}-\d{2}\.md$/,
};

// ---------------------------------------------------------------------------
// SECTION NAMES
// ---------------------------------------------------------------------------
// Each key maps a canonical section name to all known variants found in real
// notes. The parser normalises headers to the canonical key before routing.

const SECTIONS = {
  // Sections routed automatically — no interactive digest
  voirLireEcouter: ["Voir, lire, écouter", "Voir, Lire, Écouter", "Voir, Lire, Ecouter"],
  aPartager: ["À partager", "A partager"],

  // Sections copied directly into 🏠 Accueil without digest
  contacter: ["Contacter"],
  enCours: ["EN COURS", "En cours"],

  // Sections sent to the interactive digest
  digest: [
    "À faire - projets IT",
    "À faire - projets",        // legacy variant
    "À faire - projets créatifs",
    "À la maison - sur l'ordi",
    "À la maison - autres",
  ],
};

// ---------------------------------------------------------------------------
// BOLD LABEL ROUTING TABLE (section "Voir, lire, écouter" only)
// ---------------------------------------------------------------------------
// Keys are lowercase for case-insensitive matching.
// Each key maps to the destination file path defined in PATHS.

const LABEL_ROUTING = {
  // À voir
  netflix: PATHS.aVoir,
  "disney+": PATHS.aVoir,
  youtube: PATHS.aVoir,
  vidéo: PATHS.aVoir,
  video: PATHS.aVoir,
  cinéma: PATHS.aVoir,
  cinema: PATHS.aVoir,
  film: PATHS.aVoir,
  série: PATHS.aVoir,
  serie: PATHS.aVoir,
  tv: PATHS.aVoir,
  arte: PATHS.aVoir,

  // À lire
  article: PATHS.aLire,
  blog: PATHS.aLire,
  magazine: PATHS.aLire,
  journal: PATHS.aLire,

  // À écouter
  podcast: PATHS.aEcouter,
  musique: PATHS.aEcouter,
  audiobook: PATHS.aEcouter,

  // Autres
  "site web": PATHS.autres,
  "jeu vidéo": PATHS.autres,
  "jeu video": PATHS.autres,
  outil: PATHS.autres,
};

// Fallback destination when a bold label in "Voir, lire, écouter" is not
// recognised, or when the item has no bold label at all.
const LABEL_FALLBACK = PATHS.autres;

// ---------------------------------------------------------------------------
// REMINDERS INBOX
// ---------------------------------------------------------------------------
// Path to the intermediate file exported from the iPhone Reminders app.
// This file is generated by an AppleScript or Shortcuts automation and read
// by the digest as an additional source of untriaged items.

const REMINDERS = {
  inboxExportPath: path.join(VAULT_ROOT, "ressources/reminders-inbox.txt"),
  listName: "📥 Inbox",
};

// ---------------------------------------------------------------------------
// DIGEST THRESHOLDS
// ---------------------------------------------------------------------------

const DIGEST = {
  maxToday: 3,
  maxSoon: 5,
  // "Later" has no upper limit
};

module.exports = {
  PATHS,
  DAILY_NOTES,
  SECTIONS,
  LABEL_ROUTING,
  LABEL_FALLBACK,
  REMINDERS,
  DIGEST,
};